<!-- src/views/DataPolicyPage.vue -->
<template>
    <MainLayout>
      <HeroSection
        title="Data Policy"
        subtitle="Understanding how we handle and process data within the GenAI Labs platform."
        bgShape="none"
      />
      <section class="section text-content-section">
        <div class="container">
          <h2 class="section-title">Our Approach to <span class="gradient-text">Data</span></h2>
          <div class="content-prose">
            <h3>1. Data You Provide</h3>
            <p>When you use our Service, you may provide us with data, such as text prompts, code snippets, images, datasets for training, or other inputs ("User Data"). You retain ownership of your User Data.</p>
            <p>We use User Data solely to provide and improve the Service, including training and refining our AI models. We do not use your User Data for marketing or sell it to third parties.</p>
  
            <h3>2. Data Security</h3>
            <p>We implement industry-standard security measures to protect User Data from unauthorized access, disclosure, alteration, or destruction. These measures include encryption, access controls, and regular security audits.</p>
            <p>However, no method of transmission over the Internet or electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your User Data, we cannot guarantee its absolute security.</p>
  
            <h3>3. Data Retention</h3>
            <p>We retain User Data only for as long as necessary to provide the Service, comply with our legal obligations, resolve disputes, and enforce our agreements. Specific retention periods may vary depending on the type of data and the context.</p>
            <p>You can typically delete your User Data through the Service interface or by contacting support. Please note that some residual data may remain in backups for a limited period.</p>
  
            <h3>4. Model Training Data</h3>
            <p>Data used to train our general-purpose AI models is sourced from publicly available datasets, licensed datasets, and data generated by GenAI Labs. We take steps to ensure this training data is diverse and handled responsibly.</p>
            <p>User Data provided specifically for fine-tuning or custom model training is isolated and used exclusively for that purpose, unless otherwise agreed upon.</p>
  
            <h3>5. Subprocessors</h3>
            <p>We may use third-party service providers (subprocessors) to assist in providing the Service (e.g., cloud hosting, infrastructure). We maintain agreements with these subprocessors that include data protection obligations consistent with this policy.</p>
  
            <h3>6. Policy Updates</h3>
            <p>We may update this Data Policy periodically. We encourage you to review this policy regularly for any changes.</p>
  
            <p><em>Last Updated: {{ new Date().toLocaleDateString() }}</em></p>
          </div>
        </div>
      </section>
    </MainLayout>
  </template>
  
  <script>
  import MainLayout from '../layouts/MainLayout.vue';
  import HeroSection from '../components/HeroSection.vue';
  
  export default {
    name: 'DataPolicyPage',
    components: {
      MainLayout,
      HeroSection
    }
  };
  </script>
  
  <style scoped>
  /* Reusing styles from PrivacyPolicyPage example */
  .text-content-section {
    background-color: rgba(31, 41, 63, 0.1);
    padding-bottom: 6rem;
  }
  
  .content-prose {
    max-width: 800px;
    margin: 0 auto;
    line-height: 1.8;
    opacity: 0.9;
    color: var(--color-text);
  }
  
  .content-prose h3 {
    margin-top: 2.5rem;
    margin-bottom: 1rem;
    font-size: 1.6rem;
    font-weight: 600;
    color: var(--color-primary);
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
    padding-bottom: 0.5rem;
  }
  .content-prose h3:first-child {
      margin-top: 0;
  }
  
  .content-prose p {
    margin-bottom: 1.5rem;
  }
  
  .content-prose ul {
    list-style: disc;
    margin-left: 2rem;
    margin-bottom: 1.5rem;
  }
  
  .content-prose li {
    margin-bottom: 0.5rem;
  }
  
  .content-prose em {
      display: block;
      margin-top: 3rem;
      font-style: italic;
      opacity: 0.7;
      text-align: center;
  }
  </style>